import React from "react";
import "./erroroage.css";


function ErrorPage() {
    return (
        <>
            <div className="Error-page">
                <div className="back-ground-page">
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                    <div className="snow"></div>
                </div>
                <div className="error4">
                    <h2 className="error">Error Page</h2>
                    <section className="error-container">
                        <span className="four"><span className="screen-reader-text">4</span></span>
                        <span className="zero"><span className="screen-reader-text">0</span></span>
                        <span className="four"><span className="screen-reader-text">4</span></span>
                    </section>
                    <div className="link-container">
                        <a href="/" className="more-link">Go Home</a>
                    </div>
                </div>
            </div>
        </>
    );
}


export default ErrorPage;
/* 199 */